[default.extend-words]
Stonefall = "Stonefall"
Devvit = "Devvit"
Tron = "Tron"
Jenga = "Jenga"
Stack = "Stack"
Tetris = "Tetris"
redditors = "redditors"
Redis = "Redis"
framerates = "framerates"
playtest = "playtest"
js = "js"
