import type { FactionId } from './factions';
import type { KeepRecord, LandHold } from './territory';
import type { Block, DropInput } from '../simulation/types';

export type { FactionId };

/**
 * A recorded run: the seed and the taps, and nothing about the outcome.
 *
 * The only thing that reproduces a run, and now the only thing the server is sent about one.
 */
export interface ReplayData {
  version: number;
  seed: number;
  gameMode: string;
  inputs: DropInput[];
}

/**
 * The wire contract between the client and the server.
 *
 * The rule that keeps it small: the server computes outcomes, the client reports actions. A
 * request says what the player did; a response says what that turned out to be worth. Nothing
 * about a score travels client to server.
 */

/** One block of a finished tower. Fixed-point: 1000 units = one world unit. */
export interface TowerBlock {
  x: number;
  y: number;
  z?: number;
  rotation: number;
  width: number;
  depth?: number;
  height: number;
}

/** A tower standing on the grid, as the board draws it. */
export interface TowerMapEntry {
  sessionId: string;
  userId: string;
  username: string;
  score: number;
  blockCount: number;
  /** Perfect placements in the run that built it. */
  perfectStreak: number;
  /** Longest chain of consecutive perfects in that run. */
  maxCombo?: number;
  gameMode: string;
  timestamp: number;
  /**
   * The geometry. Empty when the board has spent its block budget on nearer towers, in which
   * case `height` still lets the board draw a silhouette and the map still shows the hold.
   */
  towerBlocks: TowerBlock[];
  /** Fixed-point height of the whole tower. Present so an entry without geometry still stands. */
  height?: number;
  /** The colour the tower was built under. Null for towers from before factions. */
  faction?: FactionId | null;
  worldX?: number;
  worldZ?: number;
  gridX?: number;
  gridZ?: number;
  /**
   * Vertical offset when this tower is stacked on others in the same cell: the summed height of
   * everything below it. Fixed-point, same scale as TowerBlock; divide by 1000 to render.
   */
  stackBaseY?: number;
}

/**
 * Saving a run.
 *
 * The request carries the seed and the taps, and nothing else about how it went. The server
 * replays those inputs through the shared deterministic simulation and derives the score, the
 * block count and the geometry itself, so there is no outcome field here to forge. `sessionId`
 * is generated by the client purely so a retried save is recognised as the same run rather than
 * stored twice.
 */
export type SaveRunRequest = {
  sessionId: string;
  seed: number;
  gameMode: string;
  inputs: DropInput[];
};

export type SaveRunResponse = {
  type: 'save_run';
  success: boolean;
  message?: string;
  sessionId?: string;
  /** What the server's replay scored. This is the number, not the one the client had. */
  score?: number;
  blockCount?: number;
  perfectCount?: number;
  maxCombo?: number;
  towerBlocks?: TowerBlock[];
  isPersonalBest?: boolean;
  faction?: FactionId | null;
};

export interface GridPlacement {
  /** Session id of the run being placed. */
  sessionId: string;
  gridX: number;
  gridZ: number;
  /** Position within the cell's stack, 0 = on the ground. Only keeps stack. */
  stackIndex: number;
  /** Vertical extent, fixed-point, used to offset whatever sits above it. */
  height: number;
  placedAt: number;
  /** Where it stands. Absent on records from before territory, which were all keep cells. */
  kind?: 'keep' | 'land';
}

export interface PlayerGrid {
  userId: string;
  username: string;
  placements: GridPlacement[];
  updatedAt: number;
}

/**
 * Where a player's plot sits in the shared grid.
 *
 * Placement coordinates are global, so the client needs this to know where its keep is and
 * where to point the camera. `radius` is the whole plot, keep and land together.
 */
export interface PlayerRegion {
  rx: number;
  rz: number;
  centerX: number;
  centerZ: number;
  radius: number;
}

/** The player: identity, plot and colour. Null grid and region until they have entered. */
export type GetMeResponse = {
  type: 'me';
  userId: string | null;
  username: string | null;
  grid: PlayerGrid | null;
  region: PlayerRegion | null;
  faction: FactionId | null;
  /** True once the player has chosen a colour rather than being handed one. */
  chosen: boolean;
};

/** Claim a plot. Idempotent: returns the plot the player already has. */
export type EnterResponse = {
  type: 'enter';
  success: boolean;
  message?: string;
  region?: PlayerRegion;
  faction?: FactionId;
};

export type SetFactionRequest = { faction: FactionId };
export type SetFactionResponse = {
  type: 'faction';
  success: boolean;
  faction?: FactionId;
  message?: string;
  /**
   * Session ids of the towers that came down with the switch. A colour is a side, and changing
   * sides costs everything standing under the old one on today's map.
   */
  razed?: string[];
};

/**
 * Which day's map a post shows.
 *
 * The map resets every day: each daily post holds one day's board, and the day before is closed
 * and read-only. Posts from before daily maps carry no day and always show today's.
 */
export interface MapInfo {
  /** The day the map opened, YYYY-MM-DD in UTC. */
  day: string;
  /** False once a newer day's map has opened. A closed map can be looked at, not built on. */
  live: boolean;
  /** Today's map post, so a closed map can send people to it. Null when none is known. */
  todayPostId: string | null;
}

/** Everything standing on the shared grid, capped by tower and block count, plus the keeps. */
export type GetBoardResponse = {
  type: 'board';
  towers: TowerMapEntry[];
  keeps: KeepRecord[];
  totalCount: number;
  map: MapInfo;
};

export type PlaceTowerRequest = {
  sessionId: string;
  gridX: number;
  gridZ: number;
};

/** What raising a tower did, so the client can announce it. */
export type RaiseKind = 'keep' | 'claim' | 'take';

export type PlaceTowerResponse = {
  type: 'place_tower';
  success: boolean;
  message?: string;
  grid?: PlayerGrid;
  kind?: RaiseKind;
  /** Set for `take`: whose tower toppled. */
  took?: { userId: string; username: string; score: number; faction: FactionId | null };
  /** Set when the cell could not be taken: the score standing there. */
  bar?: number;
};

export type RemovePlacementRequest = {
  sessionId: string;
};

export type RemovePlacementResponse = {
  type: 'remove_placement';
  success: boolean;
  message?: string;
  grid?: PlayerGrid;
};

// ---------------------------------------------------------------------------
// Community
//
// A run is announced as a comment on the game post, by the player, from a fixed
// set of phrasings. See src/server/core/socialService.ts for why it is a comment
// and not a post, and why the player never writes the text.
// ---------------------------------------------------------------------------

/**
 * Which fixed phrasing a brag uses. `passed` and `took` are the ones that name somebody;
 * `claimed` names a cell.
 */
export type BragKind = 'plain' | 'best' | 'first' | 'passed' | 'claimed' | 'took' | 'fell';

export interface BragRecord {
  username: string;
  faction?: FactionId | null;
  score: number;
  blocks: number;
  perfectStreak: number;
  kind: BragKind;
  commentId: string;
  permalink: string | null;
  timestamp: number;
  /** Only set for `passed` and `took`: whose score this run went by. */
  passedUsername?: string;
  /** Only set for `claimed` and `took`: the cell. */
  cell?: { x: number; z: number };
}

export interface BragRequest {
  sessionId: string;
  kind: BragKind;
  passedUsername?: string;
  passedScore?: number;
  cell?: { x: number; z: number };
}

export interface BragResponse {
  type: 'brag';
  success: boolean;
  message?: string;
  record?: BragRecord;
}

export interface GetFeedResponse {
  type: 'feed';
  brags: BragRecord[];
}

// ---------------------------------------------------------------------------
// Relay: the shared daily towers.
//
// One post per day holding as many towers as it needs. A tower's crew is at
// most a handful of people taking turns adding a block; when every crew is
// full, the next person starts a new tower. A full miss puts you out for the
// day and heals the top for the next person.
// ---------------------------------------------------------------------------

export interface RelayPlayer {
  userId: string;
  username: string;
  faction: FactionId | null;
  snoovatar: string | null;
  /** First time they were seen in the post today. */
  joinedAt: number;
  /** The tower they hold a seat on. Null while they are only watching. */
  tower?: number | null | undefined;
  /** When they took that seat: their place in the crew's rotation. */
  seatedAt?: number | undefined;
  /** Turns in a row that ran out on them. Two and the seat is given up for someone present. */
  idle?: number | undefined;
  /** Towers they have laid a block on, so each tower counts its builders once. */
  laidOn?: number[] | undefined;
  /** Blocks this player has landed today. */
  blocks: number;
  perfects: number;
  /** Set when they missed: at which block, and when. */
  out?: { block: number; at: number } | undefined;
}

export interface RelayTurn {
  userId: string;
  username: string;
  /** Index the block will occupy; also how many blocks are standing. */
  index: number;
  /** Server time the turn began. */
  startedAt: number;
  /** Server time it is forfeited. */
  endsAt: number;
}

/** Where a missed block was when it was dropped: simulation-local, fixed-point, centre. */
export interface RelayMissedBlock {
  x: number;
  y: number;
  z: number;
  width: number;
  depth: number;
  height: number;
}

/** One thing that happened, for the ticker and for everyone watching. */
export interface RelayEvent {
  at: number;
  kind: 'landed' | 'perfect' | 'fell' | 'healed' | 'opened' | 'closed' | 'joined';
  username: string;
  block: number;
  /** Who it was, drawn: set on falls, so everyone can watch the player go. */
  faction?: FactionId | null | undefined;
  snoovatar?: string | null | undefined;
  /** Set on falls: the block that went over the edge, so every client can drop it. */
  missed?: RelayMissedBlock | undefined;
}

/** Another tower in the post, as much as the scene and the pager need. */
export interface RelayTowerSummary {
  id: number;
  /** Blocks standing. */
  height: number;
  /**
   * The colour of every block, one character each: '0' for none, otherwise the faction's
   * position in FACTION_IDS plus one. A few hundred bytes for a tall tower, so a neighbour can
   * be drawn in its colours without sending its geometry.
   */
  colors: string;
  /** Crew here right now. */
  crew: number;
  /** Whoever holds the turn, if anyone. */
  turnUser: string | null;
  builders: number;
  fallen: number;
  closed: boolean;
  version: number;
}

export interface RelayState {
  postId: string;
  /** The day, as YYYY-MM-DD in UTC. */
  day: string;
  /** Which tower this view is of: the caller's own seat, or the one they are watching. */
  tower: number;
  /** Standing blocks of that tower, fixed-point, simulation-local. */
  blocks: Block[];
  /** The colour each block was laid under, index-aligned with `blocks`. The base is null. */
  colors: (FactionId | null)[];
  turn: RelayTurn | null;
  /** That tower's crew who are here, in turn order starting with whoever holds the turn. */
  lobby: RelayPlayer[];
  /** People who have laid a block on this tower today. */
  builders: number;
  fallen: number;
  /** Server clock at the time of the response, so clients can align the turn timer. */
  now: number;
  /** Set once the day is over and a newer post exists. */
  closed: boolean;
  events: RelayEvent[];
  /** The caller's own record, once they have been seen. */
  me: RelayPlayer | null;
  /** Monotonic per tower, bumped on every change; a client with an older version refetches. */
  version: number;
  /** Every tower in the post, including this one. */
  towers: RelayTowerSummary[];
  /** Most people one crew holds. */
  crewMax: number;
}

export type RelayStateResponse = { type: 'relay'; state: RelayState };

export type RelayDropRequest = { tick: number; index: number };

export type RelayDropResponse = {
  type: 'relay_drop';
  success: boolean;
  message?: string;
  /** What the drop did. */
  result?: 'landed' | 'perfect' | 'fell';
  state?: RelayState;
};

/** Take a seat: on the tower being watched if it has room, otherwise wherever there is room. */
export type RelayJoinRequest = { tower?: number };

export type RelayJoinResponse = {
  type: 'relay_join';
  success: boolean;
  message?: string;
  /** True when every crew was full and this join started a new tower. */
  started?: boolean;
  state?: RelayState;
};

/**
 * Pushed over realtime after every change to a tower. Small: a client refetches when it concerns
 * the tower it is looking at, and otherwise just redraws the neighbour from the summary.
 */
export type RelayPush = {
  kind: 'relay';
  tower: number;
  version: number;
  /** The event that caused it, for immediate feedback before the refetch lands. */
  event?: RelayEvent;
  turn?: RelayTurn | null;
  summary?: RelayTowerSummary;
};

export type RelayBragResponse = { type: 'relay_brag'; success: boolean; message?: string };

export type { KeepRecord, LandHold };
