import type { FactionId } from './factions';
import type { KeepRecord, LandHold } from './territory';
import type { Block, DropInput } from '../simulation/types';

export type { FactionId };

/**
 * A recorded run: the seed and the taps, and nothing about the outcome.
 *
 * The only thing that reproduces a run, and now the only thing the server is sent about one.
 */
export interface ReplayData {
  version: number;
  seed: number;
  gameMode: string;
  inputs: DropInput[];
}

/**
 * The wire contract between the client and the server.
 *
 * The rule that keeps it small: the server computes outcomes, the client reports actions. A
 * request says what the player did; a response says what that turned out to be worth. Nothing
 * about a score travels client to server.
 */

/** One block of a finished tower. Fixed-point: 1000 units = one world unit. */
export interface TowerBlock {
  x: number;
  y: number;
  z?: number;
  rotation: number;
  width: number;
  depth?: number;
  height: number;
}

/** A tower standing on the grid, as the board draws it. */
export interface TowerMapEntry {
  sessionId: string;
  userId: string;
  username: string;
  score: number;
  blockCount: number;
  /** Perfect placements in the run that built it. */
  perfectStreak: number;
  /** Longest chain of consecutive perfects in that run. */
  maxCombo?: number;
  gameMode: string;
  timestamp: number;
  /**
   * The geometry. Empty when the board has spent its block budget on nearer towers, in which
   * case `height` still lets the board draw a silhouette and the map still shows the hold.
   */
  towerBlocks: TowerBlock[];
  /** Fixed-point height of the whole tower. Present so an entry without geometry still stands. */
  height?: number;
  /** The colour the tower was built under. Null for towers from before factions. */
  faction?: FactionId | null;
  worldX?: number;
  worldZ?: number;
  gridX?: number;
  gridZ?: number;
  /**
   * Vertical offset when this tower is stacked on others in the same cell: the summed height of
   * everything below it. Fixed-point, same scale as TowerBlock; divide by 1000 to render.
   */
  stackBaseY?: number;
}

/**
 * Saving a run.
 *
 * The request carries the seed and the taps, and nothing else about how it went. The server
 * replays those inputs through the shared deterministic simulation and derives the score, the
 * block count and the geometry itself, so there is no outcome field here to forge. `sessionId`
 * is generated by the client purely so a retried save is recognised as the same run rather than
 * stored twice.
 */
export type SaveRunRequest = {
  sessionId: string;
  seed: number;
  gameMode: string;
  inputs: DropInput[];
};

export type SaveRunResponse = {
  type: 'save_run';
  success: boolean;
  message?: string;
  sessionId?: string;
  /** What the server's replay scored. This is the number, not the one the client had. */
  score?: number;
  blockCount?: number;
  perfectCount?: number;
  maxCombo?: number;
  towerBlocks?: TowerBlock[];
  isPersonalBest?: boolean;
  faction?: FactionId | null;
};

export interface GridPlacement {
  /** Session id of the run being placed. */
  sessionId: string;
  gridX: number;
  gridZ: number;
  /** Position within the cell's stack, 0 = on the ground. Only keeps stack. */
  stackIndex: number;
  /** Vertical extent, fixed-point, used to offset whatever sits above it. */
  height: number;
  placedAt: number;
  /** Where it stands. Absent on records from before territory, which were all keep cells. */
  kind?: 'keep' | 'land';
}

export interface PlayerGrid {
  userId: string;
  username: string;
  placements: GridPlacement[];
  updatedAt: number;
}

/**
 * Where a player's plot sits in the shared grid.
 *
 * Placement coordinates are global, so the client needs this to know where its keep is and
 * where to point the camera. `radius` is the whole plot, keep and land together.
 */
export interface PlayerRegion {
  rx: number;
  rz: number;
  centerX: number;
  centerZ: number;
  radius: number;
}

/** The player: identity, plot and colour. Null grid and region until they have entered. */
export type GetMeResponse = {
  type: 'me';
  userId: string | null;
  username: string | null;
  grid: PlayerGrid | null;
  region: PlayerRegion | null;
  faction: FactionId | null;
  /** True once the player has chosen a colour rather than being handed one. */
  chosen: boolean;
};

/** Claim a plot. Idempotent: returns the plot the player already has. */
export type EnterResponse = {
  type: 'enter';
  success: boolean;
  message?: string;
  region?: PlayerRegion;
  faction?: FactionId;
};

export type SetFactionRequest = { faction: FactionId };
export type SetFactionResponse = {
  type: 'faction';
  success: boolean;
  faction?: FactionId;
  message?: string;
};

/** Everything standing on the shared grid, capped by tower and block count, plus the keeps. */
export type GetBoardResponse = {
  type: 'board';
  towers: TowerMapEntry[];
  keeps: KeepRecord[];
  totalCount: number;
};

export type PlaceTowerRequest = {
  sessionId: string;
  gridX: number;
  gridZ: number;
};

/** What raising a tower did, so the client can announce it. */
export type RaiseKind = 'keep' | 'claim' | 'take';

export type PlaceTowerResponse = {
  type: 'place_tower';
  success: boolean;
  message?: string;
  grid?: PlayerGrid;
  kind?: RaiseKind;
  /** Set for `take`: whose tower toppled. */
  took?: { userId: string; username: string; score: number; faction: FactionId | null };
  /** Set when the cell could not be taken: the score standing there. */
  bar?: number;
};

export type RemovePlacementRequest = {
  sessionId: string;
};

export type RemovePlacementResponse = {
  type: 'remove_placement';
  success: boolean;
  message?: string;
  grid?: PlayerGrid;
};

// ---------------------------------------------------------------------------
// Community
//
// A run is announced as a comment on the game post, by the player, from a fixed
// set of phrasings. See src/server/core/socialService.ts for why it is a comment
// and not a post, and why the player never writes the text.
// ---------------------------------------------------------------------------

/**
 * Which fixed phrasing a brag uses. `passed` and `took` are the ones that name somebody;
 * `claimed` names a cell.
 */
export type BragKind = 'plain' | 'best' | 'first' | 'passed' | 'claimed' | 'took' | 'fell';

export interface BragRecord {
  username: string;
  faction?: FactionId | null;
  score: number;
  blocks: number;
  perfectStreak: number;
  kind: BragKind;
  commentId: string;
  permalink: string | null;
  timestamp: number;
  /** Only set for `passed` and `took`: whose score this run went by. */
  passedUsername?: string;
  /** Only set for `claimed` and `took`: the cell. */
  cell?: { x: number; z: number };
}

export interface BragRequest {
  sessionId: string;
  kind: BragKind;
  passedUsername?: string;
  passedScore?: number;
  cell?: { x: number; z: number };
}

export interface BragResponse {
  type: 'brag';
  success: boolean;
  message?: string;
  record?: BragRecord;
}

export interface GetFeedResponse {
  type: 'feed';
  brags: BragRecord[];
}

// ---------------------------------------------------------------------------
// Relay: the shared daily tower.
//
// One tower per daily post. Whoever is in the post takes turns adding a block;
// a full miss puts you out for the day and heals the top for the next person.
// ---------------------------------------------------------------------------

export interface RelayPlayer {
  userId: string;
  username: string;
  faction: FactionId | null;
  snoovatar: string | null;
  joinedAt: number;
  /** Blocks this player has landed today. */
  blocks: number;
  perfects: number;
  /** Set when they missed: at which block, and when. */
  out?: { block: number; at: number } | undefined;
}

export interface RelayTurn {
  userId: string;
  username: string;
  /** Index the block will occupy; also how many blocks are standing. */
  index: number;
  /** Server time the turn began. */
  startedAt: number;
  /** Server time it is forfeited. */
  endsAt: number;
}

/** One thing that happened, for the ticker. */
export interface RelayEvent {
  at: number;
  kind: 'landed' | 'perfect' | 'fell' | 'healed' | 'opened' | 'closed';
  username: string;
  block: number;
}

export interface RelayState {
  postId: string;
  /** The day, as YYYY-MM-DD in UTC. */
  day: string;
  /** Standing blocks of the shared tower, fixed-point, simulation-local. */
  blocks: Block[];
  /** The colour each block was laid under, index-aligned with `blocks`. The base is null. */
  colors: (FactionId | null)[];
  turn: RelayTurn | null;
  /** Players present, in turn order. */
  lobby: RelayPlayer[];
  /** How many people have played today, present or not. */
  builders: number;
  fallen: number;
  /** Server clock at the time of the response, so clients can align the turn timer. */
  now: number;
  /** Set once the day is over and a newer post exists. */
  closed: boolean;
  events: RelayEvent[];
  /** The caller's own record, if they have joined. */
  me: RelayPlayer | null;
  /** Monotonic, bumped on every change; a client with an older version refetches. */
  version: number;
}

export type RelayStateResponse = { type: 'relay'; state: RelayState };

export type RelayDropRequest = { tick: number; index: number };

export type RelayDropResponse = {
  type: 'relay_drop';
  success: boolean;
  message?: string;
  /** What the drop did. */
  result?: 'landed' | 'perfect' | 'fell';
  state?: RelayState;
};

/** Pushed over realtime after every change. Small: clients fetch the state on a version gap. */
export type RelayPush = {
  kind: 'relay';
  version: number;
  /** The event that caused it, for immediate feedback before the refetch lands. */
  event?: RelayEvent;
  /** The block that landed, so spectators can draw it before the state arrives. */
  block?: Block;
  blockFaction?: FactionId | null;
  turn?: RelayTurn | null;
  healed?: boolean;
};

export type RelayBragResponse = { type: 'relay_brag'; success: boolean; message?: string };

export type { KeepRecord, LandHold };
