import type { PlayerColorChoice } from './playerColors';
import type { DropInput } from '../simulation/types';

export type { PlayerColorChoice };

/**
 * A recorded run: the seed and the taps, and nothing about the outcome.
 *
 * The only thing that reproduces a run, and now the only thing the server is sent about one.
 */
export interface ReplayData {
  version: number;
  seed: number;
  gameMode: string;
  inputs: DropInput[];
}

/**
 * The wire contract between the client and the server.
 *
 * This file used to carry sixty-seven lines of tournament and Elo types with no writer and no
 * reader, a leaderboard response nothing fetched, a share request whose `username` was required
 * and then ignored, and two routes the client called every session whose responses had no type
 * at all. Everything here is now used by both sides.
 *
 * The rule that keeps it that way: the server computes outcomes, the client reports actions. A
 * request says what the player did; a response says what that turned out to be worth. Nothing
 * about a score travels client to server.
 */

/** One block of a finished tower. Fixed-point: 1000 units = one world unit. */
export interface TowerBlock {
  x: number;
  y: number;
  z?: number;
  rotation: number;
  width: number;
  depth?: number;
  height: number;
}

/** A tower standing on the grid, as the board draws it. */
export interface TowerMapEntry {
  sessionId: string;
  userId: string;
  username: string;
  score: number;
  blockCount: number;
  /** Perfect placements in the run that built it. */
  perfectStreak: number;
  /** Longest chain of consecutive perfects in that run. */
  maxCombo?: number;
  gameMode: string;
  timestamp: number;
  towerBlocks: TowerBlock[];
  playerColorChoice?: PlayerColorChoice | null;
  worldX?: number;
  worldZ?: number;
  gridX?: number;
  gridZ?: number;
  /**
   * Vertical offset when this tower is stacked on others in the same cell: the summed height of
   * everything below it. Fixed-point, same scale as TowerBlock; divide by 1000 to render.
   */
  stackBaseY?: number;
}

/**
 * Saving a run.
 *
 * The request carries the seed and the taps, and nothing else about how it went. The server
 * replays those inputs through the shared deterministic simulation and derives the score, the
 * block count and the geometry itself, so there is no outcome field here to forge. `sessionId`
 * is generated by the client purely so a retried save is recognised as the same run rather than
 * stored twice.
 */
export type SaveRunRequest = {
  sessionId: string;
  seed: number;
  gameMode: string;
  inputs: DropInput[];
  colorChoice?: PlayerColorChoice | null;
};

export type SaveRunResponse = {
  type: 'save_run';
  success: boolean;
  message?: string;
  sessionId?: string;
  /** What the server's replay scored. This is the number, not the one the client had. */
  score?: number;
  blockCount?: number;
  perfectCount?: number;
  maxCombo?: number;
  towerBlocks?: TowerBlock[];
  isPersonalBest?: boolean;
};

export type TowerColorTotals = Record<
  PlayerColorChoice | 'unknown',
  {
    count: number;
    percentage: number;
  }
>;

export type GetTowerColorStatsResponse = {
  type: 'tower_color_stats';
  totalCount: number;
  colorTotals: TowerColorTotals;
  leadingColor: PlayerColorChoice | 'tie' | 'unknown';
};

export interface GridPlacement {
  /** Session id of the run being placed. */
  sessionId: string;
  gridX: number;
  gridZ: number;
  /** Position within the cell's stack, 0 = on the ground. */
  stackIndex: number;
  /** Vertical extent, fixed-point, used to offset whatever sits above it. */
  height: number;
  placedAt: number;
}

export interface PlayerGrid {
  userId: string;
  username: string;
  placements: GridPlacement[];
  updatedAt: number;
}

/**
 * Where a player's buildable area sits in the shared grid.
 *
 * Placement coordinates are global, so the client needs this to know which cells the player may
 * build on and where to point the camera.
 */
export interface PlayerRegion {
  rx: number;
  rz: number;
  centerX: number;
  centerZ: number;
  radius: number;
}

export type GetPlayerGridResponse = {
  type: 'player_grid';
  grid: PlayerGrid | null;
  region: PlayerRegion | null;
};

/** The player's own plot, with the towers already resolved for drawing. */
export type GetPlayerBoardResponse = {
  type: 'player_board';
  grid: PlayerGrid | null;
  region: PlayerRegion | null;
  towers: TowerMapEntry[];
};

/** Everything standing on the shared grid, capped by tower and block count. */
export type GetCommunityBoardResponse = {
  type: 'community_board';
  towers: TowerMapEntry[];
  totalCount: number;
};

export type PlaceTowerRequest = {
  sessionId: string;
  gridX: number;
  gridZ: number;
};

export type PlaceTowerResponse = {
  type: 'place_tower';
  success: boolean;
  message?: string;
  grid?: PlayerGrid;
};

export type RemovePlacementRequest = {
  sessionId: string;
};

export type RemovePlacementResponse = {
  type: 'remove_placement';
  success: boolean;
  message?: string;
  grid?: PlayerGrid;
};

// ---------------------------------------------------------------------------
// Community
//
// A run is announced as a comment on the game post, by the player, from a fixed
// set of phrasings. See src/server/core/socialService.ts for why it is a comment
// and not a post, and why the player never writes the text.
// ---------------------------------------------------------------------------

/** Which fixed phrasing a brag uses. `passed` is the one that names somebody. */
export type BragKind = 'plain' | 'best' | 'first' | 'passed';

export interface BragRecord {
  username: string;
  score: number;
  blocks: number;
  perfectStreak: number;
  kind: BragKind;
  commentId: string;
  permalink: string | null;
  timestamp: number;
  /** Only set for `passed`: whose score this run went by. */
  passedUsername?: string;
}

export interface BragRequest {
  sessionId: string;
  kind: BragKind;
  score: number;
  blocks: number;
  perfectStreak: number;
  passedUsername?: string;
  passedScore?: number;
}

export interface BragResponse {
  type: 'brag';
  success: boolean;
  message?: string;
  record?: BragRecord;
}

export interface GetFeedResponse {
  type: 'feed';
  brags: BragRecord[];
}
